### ISSUE TITLE
Tensorboard-controller pod is getting struck in waiting state

### ISSUE THREAD

**Issue by JyothsnaPendyala** [canonical/kubeflow-tensorboards-operator#32]
Hello! I am trying to install charmed kubeflow. 
when I use the command "juju deploy kubeflow --trust", Tensorboard-controller is getting struck in waiting state.
Tensorboard-controller is not in the kube-lite. So if I try to deploy that charm seperately using https://github.com/canonical/kubeflow-tensorboards-operator , My whole kubeflow environment is becoming slow.
can you please help me with this?
![image](https://user-images.githubusercontent.com/100350083/196939915-6010f7ac-3704-4cd2-936e-99c525b4e1cf.png)

**Comment by misohu** [comment]
Hi, thanks for reaching out. Problem is that the Gateway resource is not created during installation. Please run the 
```
juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"
```
(I recommend waiting a little after the juju deploy kubeflow command). You can check that the gateway was created with `kubectl get gateway -A`

We already have issue for this here: https://github.com/canonical/istio-operators/issues/113
